import type { Metadata } from "next";
import localFont from "next/font/local";
import NestedLayout from "@/components/NestedLayout";
import "../styles/globals.scss";
import GlobalProvider from "@/contexts/GlobalProvider";

const fontBRSonoma = localFont({
  src: [
    {
      path: "../public/fonts/BRSonoma-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/BRSonoma-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/BRSonoma-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={fontBRSonoma.className}>
        <GlobalProvider>
          <NestedLayout>{children}</NestedLayout>
        </GlobalProvider>
      </body>
    </html>
  );
}
